[tool.poetry]
name = "dapla-statbank-authenticator"
version = "0.1.0"
description = "A template repository for Python microservices targeting Kuberntes deployment"
authors = ["Statistics Norway <mmw@ssb.no>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/statisticsnorway/dapla-statbank-authenticator"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
gunicorn = "^20.1.0"
python-json-logger = "^2.0.2"
prometheus-fastapi-instrumentator = "^5.8.1"
aes-pkcs5 = "^0.1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
black = "^22.3.0"
pytest = "^7.1.2"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
pycrunch-engine = "^1.4"
requests = "^2.27.1"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
