apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dapla-statbank-authenticator
  namespace: dapla-stat
spec:
  image: {{image}}
  port: 8080

  replicas:
    max: 2
    min: 2

  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
     memory: 256Mi

  envFrom:
    - secret: dapla-statbank-authenticator-cipher-key

  liveness:
    path: "/health/liveness"
    port: 8080
    initialDelay: 10
  readiness:
    path: "/health/readiness"
    port: 8080
    initialDelay: 5

  prometheus:
    enabled: true
    path: "/metrics"

  ingresses:
    - https://statbank-authenticator.intern.test.ssb.no
