name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      endpoint: statisticsnorway

# Pipeline will be run on this base image
pool:
  vmImage: 'ubuntu-latest'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter
  # Variables defined here
  - name: appName
    value: 'dapla-statbank-authenticator'
  - name: namespace
    value: 'dapla'
  - name: sonarCloud
    value: 'bipSonarCloud'
  - name: imageNameNexus
    value: 'nexus.ssb.no:8437/prod-bip/ssb/$(namespace)/$(appName)'

jobs:
  - template: python/python-complete-build.yml@templates
    parameters:
      appName: $(appName)
      namespace: $(namespace)
      sonarCloud: $(sonarCloud)

  # Pull and retag docker image. Will only run if it is a tag-operation on the repo.
  # See https://github.com/statisticsnorway/azure-pipelines-templates/blob/master/docker/docker-tag-for-production.yml
  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: 'master-$(Build.SourceVersion)'
      gcrImageName: 'eu.gcr.io/prod-bip/ssb/$(namespace)/$(appName)'

  - job: deployToStagingOnPrem    
    pool:
      name: jupyterhub-onprem-staging
      demands:
      - agent.name -equals staging-agent

    displayName: "Deploying to staging on prem"
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
      - script: |
          set -e
          
          IMAGE=${{ variables.imageNameNexus }}:latest
          echo "Pulling $IMAGE"
          docker pull $IMAGE
          echo "Removing dangling images"
          docker image prune --force

