name: Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: python-tests
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
      PYTHON_VERSION: "3.13"

    steps:
      - name: Check out the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup python and uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ">=0.8.19,<1.0.0"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run python tests
        run: |
          uv sync
          uv run pytest

      - name: Show test coverage
        run: |
          uv run pytest --cov
