name: Tests

on:
  pull_request:

jobs:
  tests:
    name: python-tests
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
      PYTHON_VERSION: "3.13"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup python and uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ">=0.8.19,<1.0.0"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run python tests
        run: |
          uv sync
          uv run pytest

      - name: Show test coverage
        run: |
          uv run pytest --cov
