name: Update dependencies

on:
  schedule:
    # 07:00 on Fridays
    - cron: '0 7 * * Fri'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Print Poetry version
        run: poetry --version
      - name: Install poetry up plugin
        run: poetry self add poetry-plugin-up
      - name: Run auto dependency update
        uses: mmwinther/dependencies-autoupdate@main
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            update-command: "poetry up --latest --no-interaction"
            default-branch-name: "master"
